// Code generated by protoc-gen-main.
// source: regist/msg.go
// DO NOT EDIT!

package robots

import (
	"errors"
	"protoactor/messages"
)

//解包消息
func unpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	case 4030:
		msg := &messages.SOperate{}
		err := msg.Unmarshal(b)
		return msg, err
	case 1036:
		msg := &messages.SUserData{}
		err := msg.Unmarshal(b)
		return msg, err
	case 1000:
		msg := &messages.SLogin{}
		err := msg.Unmarshal(b)
		return msg, err
	case 3000:
		msg := &messages.SBuy{}
		err := msg.Unmarshal(b)
		return msg, err
	case 3002:
		msg := &messages.SWxpayOrder{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4025:
		msg := &messages.SGamestart{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4022:
		msg := &messages.SCamein{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4027:
		msg := &messages.SDraw{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4036:
		msg := &messages.SGameover{}
		err := msg.Unmarshal(b)
		return msg, err
	case 1004:
		msg := &messages.SWxLogin{}
		err := msg.Unmarshal(b)
		return msg, err
	case 3004:
		msg := &messages.SWxpayQuery{}
		err := msg.Unmarshal(b)
		return msg, err
	case 3006:
		msg := &messages.SBuildAgent{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4002:
		msg := &messages.SLeave{}
		err := msg.Unmarshal(b)
		return msg, err
	case 1030:
		msg := &messages.SConfig{}
		err := msg.Unmarshal(b)
		return msg, err
	case 1002:
		msg := &messages.SRegist{}
		err := msg.Unmarshal(b)
		return msg, err
	case 2004:
		msg := &messages.SChatVoice{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4004:
		msg := &messages.SReady{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4010:
		msg := &messages.SCreateRoom{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4032:
		msg := &messages.SPengKong{}
		err := msg.Unmarshal(b)
		return msg, err
	case 2000:
		msg := &messages.SChatText{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4000:
		msg := &messages.SEnterRoom{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4014:
		msg := &messages.SKick{}
		err := msg.Unmarshal(b)
		return msg, err
	case 4029:
		msg := &messages.SDiscard{}
		err := msg.Unmarshal(b)
		return msg, err
	default:
		return nil, errors.New("msg id wrong")
	}
}
