// Code generated by protoc-gen-main.
// source: regist/msg.go
// DO NOT EDIT!

package socket

import (
	"errors"
	"protoactor/messages"
)

//打包消息
func packet(msg interface{}) (uint32, []byte, error) {
	switch msg.(type) {
	case *messages.SCamein:
		b, err := msg.(*messages.SCamein).Marshal()
		return 4022, b, err
	case *messages.SDraw:
		b, err := msg.(*messages.SDraw).Marshal()
		return 4027, b, err
	case *messages.SGameover:
		b, err := msg.(*messages.SGameover).Marshal()
		return 4036, b, err
	case *messages.SWxLogin:
		b, err := msg.(*messages.SWxLogin).Marshal()
		return 1004, b, err
	case *messages.SWxpayQuery:
		b, err := msg.(*messages.SWxpayQuery).Marshal()
		return 3004, b, err
	case *messages.SBuildAgent:
		b, err := msg.(*messages.SBuildAgent).Marshal()
		return 3006, b, err
	case *messages.SLeave:
		b, err := msg.(*messages.SLeave).Marshal()
		return 4002, b, err
	case *messages.SConfig:
		b, err := msg.(*messages.SConfig).Marshal()
		return 1030, b, err
	case *messages.SRegist:
		b, err := msg.(*messages.SRegist).Marshal()
		return 1002, b, err
	case *messages.SChatVoice:
		b, err := msg.(*messages.SChatVoice).Marshal()
		return 2004, b, err
	case *messages.SReady:
		b, err := msg.(*messages.SReady).Marshal()
		return 4004, b, err
	case *messages.SCreateRoom:
		b, err := msg.(*messages.SCreateRoom).Marshal()
		return 4010, b, err
	case *messages.SPengKong:
		b, err := msg.(*messages.SPengKong).Marshal()
		return 4032, b, err
	case *messages.SChatText:
		b, err := msg.(*messages.SChatText).Marshal()
		return 2000, b, err
	case *messages.SEnterRoom:
		b, err := msg.(*messages.SEnterRoom).Marshal()
		return 4000, b, err
	case *messages.SKick:
		b, err := msg.(*messages.SKick).Marshal()
		return 4014, b, err
	case *messages.SDiscard:
		b, err := msg.(*messages.SDiscard).Marshal()
		return 4029, b, err
	case *messages.SOperate:
		b, err := msg.(*messages.SOperate).Marshal()
		return 4030, b, err
	case *messages.SUserData:
		b, err := msg.(*messages.SUserData).Marshal()
		return 1036, b, err
	case *messages.SLogin:
		b, err := msg.(*messages.SLogin).Marshal()
		return 1000, b, err
	case *messages.SBuy:
		b, err := msg.(*messages.SBuy).Marshal()
		return 3000, b, err
	case *messages.SWxpayOrder:
		b, err := msg.(*messages.SWxpayOrder).Marshal()
		return 3002, b, err
	case *messages.SGamestart:
		b, err := msg.(*messages.SGamestart).Marshal()
		return 4025, b, err
	default:
		return 0, []byte{}, errors.New("msg wrong")
	}
}
